### ISSUE TITLE
Добавить проверку правильности входных данных

### ISSUE THREAD

**Issue by BozhkoAV** [BozhkoAV/BTC-ETH-Converter#1]

**Comment by BozhkoAV** [comment]
Добавлена проверка правильности вводимой валюты и её численного количества

**Comment by borisgrafx** [comment]
Сначала посмотри сюда: #24 
А затем сюда: #25 

Теперь прочитай комментарий выше:
> Добавлена проверка правильности вводимой валюты и её численного количества

Посмотри затем, что следует дальше:

> [BozhkoAV](https://github.com/BozhkoAV)
closed this as [completed](https://github.com/BozhkoAV/BTC-ETH-Converter/issues?q=is%3Aissue%20state%3Aclosed%20archived%3Afalse%20reason%3Acompleted)[on Dec 18, 2022](https://github.com/BozhkoAV/BTC-ETH-Converter/issues/1#event-8063604914)

... и в конце подумай, а не слишком ли **рано** был **закрыт** данный _issue_?
